// mg_custom_nodes/hao-ai-lab_FastVideo_20260802/apps/fastvideo_studio/src/app/datasets/page.tsx
'use client';

import * as React from 'react';

import AddDatasetButton from '@/components/datasets/AddDatasetButton';
import CreateDatasetModal from '@/components/datasets/CreateDatasetModal';
import DatasetCard from '@/components/datasets/DatasetCard';
import { HeaderActions } from '@/components/shell/HeaderActionsContext';
import { Card } from '@/components/ui/card';
import { useStore } from '@/hooks/useStore';
import { getDatasets } from '@/lib/api';
import type { Dataset } from '@/lib/api';
import {
  setActiveDataset,
  setActiveDatasetId,
} from '@/stores/activeDataset';
import {
  createDatasetModalStore,
  setCreateDatasetModalOpen,
} from '@/stores/createDatasetModalOpen';

export default function DatasetsPage() {
  const [datasets, setDatasets] = React.useState<Dataset[]>([]);
  const [error, setError] = React.useState<string | null>(null);
  const { open } = useStore(createDatasetModalStore);

  const fetchDatasets = React.useCallback(async () => {
    try {
      setDatasets(await getDatasets());
      setError(null);
    } catch (err) {
      console.error('Failed to fetch datasets:', err);
      // Distinguish an API outage from a genuinely empty list, so the user
      // isn't told they have no datasets when the server is unreachable.
      setError(err instanceof Error ? err.message : 'Failed to load datasets');
    }
  }, []);

  React.useEffect(() => {
    fetchDatasets();
  }, [fetchDatasets]);

  function handleSelectDataset(ds: Dataset) {
    setActiveDataset(ds);
    setActiveDatasetId(ds.id);
  }

  return (
    <>
      <HeaderActions>
        <AddDatasetButton />
      </HeaderActions>
      <main className="mx-auto flex w-full max-w-[850px] flex-col gap-6 px-4 pb-12">
        <Card className="p-6">
          <div>
            {error ? (
              <p className="py-8 text-center text-destructive">{error}</p>
            ) : datasets.length === 0 ? (
              <p className="py-8 text-center text-muted-foreground">
                No datasets yet.
              </p>
            ) : (
              datasets.map((ds) => (
                <DatasetCard
                  key={ds.id}
                  dataset={ds}
                  onUpdated={fetchDatasets}
                  onSelect={() => handleSelectDataset(ds)}
                />
              ))
            )}
          </div>
        </Card>
      </main>
      <CreateDatasetModal
        isOpen={open}
        onClose={() => setCreateDatasetModalOpen(false)}
        onSuccess={() => {
          fetchDatasets();
          setCreateDatasetModalOpen(false);
        }}
      />
    </>
  );
}

// mg_custom_nodes/hao-ai-lab_FastVideo_20260407/ui/src/routes/datasets/+page.svelte
<script lang="ts">
	import { onMount, onDestroy } from "svelte";
	import { getDatasets } from "$lib/api";
	import type { Dataset } from "$lib/api";
	import CreateDatasetModal from "$lib/components/CreateDatasetModal.svelte";
	import DatasetCard from "$lib/components/DatasetCard.svelte";
	import AddDatasetButton from "$lib/components/AddDatasetButton.svelte";
	import { setHeaderActions } from "$lib/stores/headerActions";
	import {
		activeDataset,
		setActiveDataset,
		setActiveDatasetId,
	} from "$lib/stores/activeDataset";
	import { createDatasetModalOpen } from "$lib/stores/createDatasetModalOpen";

	let datasets = $state<Dataset[]>([]);

	onMount(() => {
		setHeaderActions([{ component: AddDatasetButton, props: {} }]);
	});
	onDestroy(() => setHeaderActions([]));

	async function fetchDatasets() {
		try {
			datasets = await getDatasets();
		} catch (err) {
			console.error("Failed to fetch datasets:", err);
		}
	}

	onMount(() => {
		fetchDatasets();
	});

	function handleSelectDataset(ds: Dataset) {
		setActiveDataset(ds);
		setActiveDatasetId(ds.id);
	}

	function handleCloseModal() {
		createDatasetModalOpen.set(false);
	}

	function handleSuccess() {
		fetchDatasets();
		createDatasetModalOpen.set(false);
	}
</script>

<main class="main">
	<section class="card">
		<div id="datasets-container">
			{#if datasets.length === 0}
				<p class="placeholder">No datasets yet.</p>
			{:else}
				{#each datasets as ds (ds.id)}
					<DatasetCard
						dataset={ds}
						onUpdated={fetchDatasets}
						onSelect={() => handleSelectDataset(ds)}
					/>
				{/each}
			{/if}
		</div>
	</section>
</main>
<CreateDatasetModal
	isOpen={$createDatasetModalOpen}
	onClose={handleCloseModal}
	onSuccess={handleSuccess}
/>

<style>
	.main {
		max-width: 850px;
		margin: 0 auto;
		padding: 0 1rem 3rem;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		width: 100%;
	}
	.card {
		padding: 1.5rem;
	}
	.placeholder {
		text-align: center;
		color: var(--text-dim);
		padding: 2rem 0;
	}
</style>
