// mg_custom_nodes/hao-ai-lab_FastVideo_20260403/ui/src/lib/components/DownloadCaptions.svelte
<script lang="ts">
	let { fileNames = [], captions = {} }: {
		fileNames?: string[];
		captions?: Record<string, string>;
	} = $props();

	function downloadBlob(blob: Blob, filename: string) {
		const url = URL.createObjectURL(blob);
		const a = document.createElement("a");
		a.href = url;
		a.download = filename;
		a.click();
		URL.revokeObjectURL(url);
	}

	const sortedNames = $derived([...fileNames].sort());
	const disabled = $derived(fileNames.length === 0);

	function handleDownloadJson() {
		const data = sortedNames.map((path) => ({
			path,
			cap: captions[path] ?? "",
		}));
		const blob = new Blob([JSON.stringify(data, null, 2)], {
			type: "application/json",
		});
		downloadBlob(blob, "videos2caption.json");
	}

	function handleDownloadTxt() {
		const videosContent = sortedNames.join("\n");
		const promptContent = sortedNames.map((fn) => captions[fn] ?? "").join("\n");
		downloadBlob(new Blob([videosContent], { type: "text/plain" }), "videos.txt");
		setTimeout(() => {
			downloadBlob(
				new Blob([promptContent], { type: "text/plain" }),
				"captions.txt",
			);
		}, 100);
	}

	function handleDownloadCsv() {
		const escape = (s: string) =>
			s.includes('"') || s.includes(",") || s.includes("\n")
				? `"${s.replace(/"/g, '""')}"`
				: s;
		const rows = sortedNames.map(
			(fn) => `${escape(fn)},${escape(captions[fn] ?? "")}`,
		);
		const header = "video_name,caption";
		const csv = [header, ...rows].join("\n");
		downloadBlob(new Blob([csv], { type: "text/csv" }), "captions.csv");
	}
</script>

<div class="wrapper">
	<button type="button" class="btn btnSmall trigger" disabled={disabled}>
		Download Captions
	</button>
	<div class="menu" role="menu">
		<button
			class="menuItem"
			role="menuitem"
			onclick={handleDownloadJson}
			disabled={disabled}
		>
			JSON
		</button>
		<button
			class="menuItem"
			role="menuitem"
			onclick={handleDownloadTxt}
			disabled={disabled}
		>
			TXT
		</button>
		<button
			class="menuItem"
			role="menuitem"
			onclick={handleDownloadCsv}
			disabled={disabled}
		>
			CSV
		</button>
	</div>
</div>

<style>
	.wrapper {
		position: relative;
		display: inline-block;
	}
	.trigger {
		display: flex;
		align-items: center;
		gap: 0.35rem;
	}
	.trigger::after {
		content: "";
		width: 0;
		height: 0;
		border-left: 4px solid transparent;
		border-right: 4px solid transparent;
		border-top: 5px solid currentColor;
		opacity: 0.85;
	}
	.menu {
		position: absolute;
		top: 100%;
		right: 0;
		margin-top: 0.25rem;
		min-width: 100%;
		background: var(--bg);
		border: 1px solid var(--border);
		border-radius: var(--radius);
		box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
		padding: 0.25rem 0;
		opacity: 0;
		visibility: hidden;
		transform: translateY(-4px);
		transition: opacity 0.15s, visibility 0.15s, transform 0.15s;
		z-index: 200;
	}
	.wrapper:hover .menu {
		opacity: 1;
		visibility: visible;
		transform: translateY(0);
	}
	.menuItem {
		display: block;
		width: 100%;
		padding: 0.5rem 1rem;
		border: none;
		background: transparent;
		color: var(--text);
		font-family: inherit;
		font-size: 0.9rem;
		font-weight: 500;
		text-align: left;
		cursor: pointer;
		transition: background 0.1s;
		white-space: nowrap;
	}
	.menuItem:hover {
		background: var(--border);
	}
	.menuItem:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
	.btn {
		cursor: pointer;
		border: none;
		border-radius: var(--radius);
		font-family: inherit;
		font-weight: 600;
		font-size: 0.85rem;
		padding: 0.55rem 1.2rem;
	}
	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
	.btnSmall {
		background: transparent;
		color: var(--accent-h);
		border: 1px solid var(--border);
		padding: 0.3rem 0.7rem;
		font-size: 0.8rem;
	}
</style>

// mg_custom_nodes/hao-ai-lab_FastVideo_20260801/apps/fastvideo_studio/src/components/datasets/DownloadCaptions.tsx
'use client';

import { ChevronDown } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { downloadBlob } from '@/lib/utils';

const MENU_ITEM =
  'block w-full cursor-pointer px-4 py-2 text-left text-sm font-medium text-foreground transition-colors hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50';

export default function DownloadCaptions({
  fileNames,
  captions,
}: {
  fileNames: string[];
  captions: Record<string, string>;
}) {
  const disabled = fileNames.length === 0;

  // Sorted lazily in the click handlers: this component re-renders with the
  // sidebar on every caption keystroke, and the sort is only needed on click.
  const sortedFileNames = () => [...fileNames].sort();

  function handleDownloadJson() {
    const data = sortedFileNames().map((path) => ({
      path,
      cap: captions[path] ?? '',
    }));
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: 'application/json',
    });
    downloadBlob(blob, 'videos2caption.json');
  }

  function handleDownloadTxt() {
    const sortedNames = sortedFileNames();
    const videosContent = sortedNames.join('\n');
    const promptContent = sortedNames
      .map((fn) => captions[fn] ?? '')
      .join('\n');
    downloadBlob(
      new Blob([videosContent], { type: 'text/plain' }),
      'videos.txt',
    );
    setTimeout(() => {
      downloadBlob(
        new Blob([promptContent], { type: 'text/plain' }),
        'captions.txt',
      );
    }, 100);
  }

  function handleDownloadCsv() {
    const escape = (s: string) =>
      s.includes('"') || s.includes(',') || s.includes('\n')
        ? `"${s.replace(/"/g, '""')}"`
        : s;
    const rows = sortedFileNames().map(
      (fn) => `${escape(fn)},${escape(captions[fn] ?? '')}`,
    );
    const csv = ['video_name,caption', ...rows].join('\n');
    downloadBlob(new Blob([csv], { type: 'text/csv' }), 'captions.csv');
  }

  return (
    <div className="group relative inline-block">
      <Button
        type="button"
        variant="outline"
        size="sm"
        disabled={disabled}
        aria-haspopup="menu"
        className="gap-1.5"
      >
        Download Captions
        <ChevronDown className="h-3.5 w-3.5 opacity-85" />
      </Button>
      {!disabled && (
        <div
          role="menu"
          className="invisible absolute right-0 top-full z-[200] min-w-full -translate-y-1 pt-1 opacity-0 transition-all group-focus-within:visible group-focus-within:translate-y-0 group-focus-within:opacity-100 group-hover:visible group-hover:translate-y-0 group-hover:opacity-100"
        >
          <div className="overflow-hidden rounded-lg border border-border bg-popover py-1 shadow-lg">
            <button
              type="button"
              role="menuitem"
              className={MENU_ITEM}
              onClick={handleDownloadJson}
            >
              JSON
            </button>
            <button
              type="button"
              role="menuitem"
              className={MENU_ITEM}
              onClick={handleDownloadTxt}
            >
              TXT
            </button>
            <button
              type="button"
              role="menuitem"
              className={MENU_ITEM}
              onClick={handleDownloadCsv}
            >
              CSV
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
