// mg_custom_nodes/hao-ai-lab_FastVideo_20260802/apps/fastvideo_studio/src/components/datasets/DatasetSidebar.tsx
'use client';

import * as React from 'react';
import { X } from 'lucide-react';

import DownloadCaptions from '@/components/datasets/DownloadCaptions';
import { Textarea } from '@/components/ui/textarea';
import { useResizable } from '@/hooks/useResizable';
import {
  getDatasetFiles,
  getDatasetMediaUrl,
  updateDatasetCaption,
  type Dataset,
} from '@/lib/api';
import { cn } from '@/lib/utils';

const SIDEBAR_MIN_WIDTH = 320;
const SIDEBAR_MAX_WIDTH = 900;
const INITIAL_PAGE_SIZE = 24;
const PAGE_SIZE = 24;
const SCROLL_THRESHOLD = 200;

// Memoized so a caption keystroke re-renders only the edited card, not every
// visible <video> in the grid (visibleCount grows unbounded with scrolling).
const DatasetFileCard = React.memo(function DatasetFileCard({
  fileName,
  mediaUrl,
  caption,
  thumbLoaded,
  onCaptionChange,
  onThumbLoaded,
}: {
  fileName: string;
  mediaUrl: string;
  caption: string;
  thumbLoaded: boolean;
  onCaptionChange: (fileName: string, value: string) => void;
  onThumbLoaded: (fileName: string) => void;
}) {
  return (
    <div className="relative flex flex-col overflow-hidden rounded-lg border border-border bg-background">
      {!thumbLoaded && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center bg-background/70">
          <div className="h-6 w-6 animate-spin rounded-full border-2 border-muted-foreground/40 border-t-accent-blue" />
        </div>
      )}
      {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
      <video
        src={mediaUrl}
        className="aspect-video w-full bg-border object-cover"
        muted
        autoPlay
        loop
        playsInline
        onLoadedData={() => onThumbLoaded(fileName)}
        onError={() => onThumbLoaded(fileName)}
      />
      <Textarea
        value={caption}
        onChange={(e) => onCaptionChange(fileName, e.target.value)}
        placeholder="Caption"
        rows={2}
        className="min-h-[2.5rem] resize-y rounded-none border-0 bg-transparent p-1.5 text-xs shadow-none focus-visible:border-transparent focus-visible:ring-0"
      />
    </div>
  );
});

export default function DatasetSidebar({
  dataset,
  onClose,
  onWidthChange,
}: {
  dataset: Dataset;
  onClose: () => void;
  onWidthChange?: (w: number) => void;
}) {
  const [width, setWidth] = React.useState(400);
  const [isDragging, setIsDragging] = React.useState(false);
  const [fileNames, setFileNames] = React.useState<string[]>([]);
  const [captions, setCaptions] = React.useState<Record<string, string>>({});
  const [visibleCount, setVisibleCount] = React.useState(INITIAL_PAGE_SIZE);
  const [isLoading, setIsLoading] = React.useState(true);
  const [thumbLoaded, setThumbLoaded] = React.useState<
    Record<string, boolean>
  >({});

  // Pending debounced caption saves, keyed per file so editing one caption
  // can't cancel another file's pending save.
  const pendingSaves = React.useRef(
    new Map<string, { timer: ReturnType<typeof setTimeout>; save: () => void }>(),
  );
  const scrollRef = React.useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    onWidthChange?.(width);
  }, [width, onWidthChange]);

  React.useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    getDatasetFiles(dataset.id)
      .then((data) => {
        if (cancelled) return;
        setFileNames(data.file_names);
        setCaptions(data.captions);
        setVisibleCount(INITIAL_PAGE_SIZE);
        setThumbLoaded({});
      })
      .catch((err) => console.error('Failed to load dataset files:', err))
      .finally(() => {
        if (!cancelled) setIsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [dataset.id]);

  const flushPendingSaves = React.useCallback(() => {
    for (const { timer, save } of pendingSaves.current.values()) {
      clearTimeout(timer);
      save();
    }
    pendingSaves.current.clear();
  }, []);

  // Flush (not drop) pending saves when the dataset changes or on unmount, so
  // an edit made within the debounce window of closing isn't lost.
  React.useEffect(() => flushPendingSaves, [dataset.id, flushPendingSaves]);

  const { onMouseDown } = useResizable({
    edge: 'right',
    minWidth: SIDEBAR_MIN_WIDTH,
    maxWidth: SIDEBAR_MAX_WIDTH,
    getWidth: () => width,
    onWidth: setWidth,
    onDragChange: setIsDragging,
  });

  const datasetId = dataset.id;
  const handleCaptionChange = React.useCallback(
    (fileName: string, value: string) => {
      setCaptions((prev) => ({ ...prev, [fileName]: value }));
      const pending = pendingSaves.current.get(fileName);
      if (pending) clearTimeout(pending.timer);
      const save = () => {
        updateDatasetCaption(datasetId, fileName, value).catch((err) =>
          console.error('Failed to save caption:', err),
        );
      };
      const timer = setTimeout(() => {
        pendingSaves.current.delete(fileName);
        save();
      }, 500);
      pendingSaves.current.set(fileName, { timer, save });
    },
    [datasetId],
  );

  function handleScroll() {
    const el = scrollRef.current;
    if (!el || isLoading || visibleCount >= fileNames.length) return;
    const { scrollTop, scrollHeight, clientHeight } = el;
    const distanceFromBottom = scrollHeight - (scrollTop + clientHeight);
    if (distanceFromBottom < SCROLL_THRESHOLD) {
      setVisibleCount((c) => Math.min(c + PAGE_SIZE, fileNames.length));
    }
  }

  // When the visible grid doesn't overflow (a wide/tall sidebar can fit the
  // first page without a scrollbar), no scroll event ever fires — so top up
  // visibleCount until it overflows or every file is shown. Re-runs on resize
  // (width) and after each page grows, otherwise files 25..N are unreachable.
  React.useEffect(() => {
    if (isLoading || visibleCount >= fileNames.length) return;
    const el = scrollRef.current;
    if (el && el.scrollHeight <= el.clientHeight) {
      setVisibleCount((c) => Math.min(c + PAGE_SIZE, fileNames.length));
    }
  }, [visibleCount, fileNames.length, isLoading, width]);

  const markThumbLoaded = React.useCallback((fileName: string) => {
    setThumbLoaded((prev) =>
      prev[fileName] ? prev : { ...prev, [fileName]: true },
    );
  }, []);

  const visibleFiles = fileNames.slice(0, visibleCount);

  return (
    <aside
      className="fixed bottom-0 right-0 top-[var(--header-height)] z-50 flex max-h-[calc(100vh-var(--header-height))] min-w-[320px] shrink-0 flex-col border-l border-border bg-card"
      style={{ width, maxWidth: SIDEBAR_MAX_WIDTH }}
    >
      <div className="flex shrink-0 items-center justify-between border-b border-border px-5 py-4">
        <h2 className="m-0 min-w-0 truncate text-base font-semibold text-foreground">
          {dataset.name}
        </h2>
        <div className="flex shrink-0 items-center gap-2">
          <DownloadCaptions fileNames={fileNames} captions={captions} />
          <button
            type="button"
            onClick={onClose}
            title="Close"
            aria-label="Close"
            className="flex items-center justify-center rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
          >
            <X className="h-[18px] w-[18px]" />
          </button>
        </div>
      </div>

      <div className="flex min-h-0 flex-1 flex-col overflow-hidden">
        <div
          ref={scrollRef}
          onScroll={handleScroll}
          className="flex-1 overflow-y-auto p-4"
        >
          {isLoading ? (
            <p className="p-8 text-center text-muted-foreground">Loading…</p>
          ) : fileNames.length === 0 ? (
            <p className="p-8 text-center text-muted-foreground">
              No media files
            </p>
          ) : (
            <div className="grid gap-4 [grid-template-columns:repeat(auto-fill,minmax(140px,1fr))]">
              {visibleFiles.map((fileName) => (
                <DatasetFileCard
                  key={fileName}
                  fileName={fileName}
                  mediaUrl={getDatasetMediaUrl(dataset.id, fileName)}
                  caption={captions[fileName] ?? ''}
                  thumbLoaded={!!thumbLoaded[fileName]}
                  onCaptionChange={handleCaptionChange}
                  onThumbLoaded={markThumbLoaded}
                />
              ))}
            </div>
          )}
        </div>
      </div>

      <div
        role="presentation"
        onMouseDown={onMouseDown}
        className={cn(
          'absolute bottom-0 left-0 top-0 z-[1] w-1.5 cursor-col-resize hover:bg-accent-blue/25',
          isDragging && 'bg-accent-blue/25',
        )}
      />
    </aside>
  );
}

// mg_custom_nodes/hao-ai-lab_FastVideo_20260607/ui/src/lib/components/DatasetSidebar.svelte
<script lang="ts">
	import type { Dataset } from "$lib/api";
	import {
		getDatasetFiles,
		updateDatasetCaption,
		getDatasetMediaUrl,
	} from "$lib/api";
	import DownloadCaptions from "./DownloadCaptions.svelte";
	import { resizable } from "$lib/actions/resizable";

	let { dataset, onClose, onWidthChange }: {
		dataset: Dataset;
		onClose: () => void;
		onWidthChange?: (w: number) => void;
	} = $props();

	const SIDEBAR_MIN_WIDTH = 320;
	const SIDEBAR_MAX_WIDTH = 900;
	const INITIAL_PAGE_SIZE = 24;
	const PAGE_SIZE = 24;

	let width = $state(400);
	let isDragging = $state(false);
	let fileNames = $state<string[]>([]);
	let captions = $state<Record<string, string>>({});
	let visibleCount = $state(INITIAL_PAGE_SIZE);
	let isLoading = $state(true);
	let thumbLoaded = $state<Record<string, boolean>>({});
	let saveTimeout: ReturnType<typeof setTimeout> | null = null;
	let scrollEl: HTMLDivElement;

	$effect(() => {
		onWidthChange?.(width);
	});

	$effect(() => {
		let cancelled = false;
		isLoading = true;
		getDatasetFiles(dataset.id)
			.then((data) => {
				if (!cancelled) {
					fileNames = data.file_names;
					captions = data.captions;
					visibleCount = INITIAL_PAGE_SIZE;
					thumbLoaded = {};
				}
			})
			.catch((err) => console.error("Failed to load dataset files:", err))
			.finally(() => {
				if (!cancelled) isLoading = false;
			});
		return () => {
			cancelled = true;
		};
	});

	function handleCaptionChange(fileName: string, value: string) {
		captions = { ...captions, [fileName]: value };
		if (saveTimeout) clearTimeout(saveTimeout);
		saveTimeout = setTimeout(() => {
			saveTimeout = null;
			updateDatasetCaption(dataset.id, fileName, value).catch((err) =>
				console.error("Failed to save caption:", err),
			);
		}, 500);
	}

	function handleLoadMore() {
		visibleCount = Math.min(visibleCount + PAGE_SIZE, fileNames.length);
	}

	const resizableOpts = $derived({
		edge: "right" as const,
		minWidth: SIDEBAR_MIN_WIDTH,
		maxWidth: SIDEBAR_MAX_WIDTH,
		getWidth: () => width,
		onWidth: (w: number) => (width = w),
		onDragChange: (dragging: boolean) => (isDragging = dragging),
	});

	$effect(() => {
		return () => {
			if (saveTimeout) clearTimeout(saveTimeout);
		};
	});

	const visibleFiles = $derived(fileNames.slice(0, visibleCount));
	const hasMore = $derived(visibleCount < fileNames.length);

	function handleScroll() {
		if (!hasMore || isLoading || !scrollEl) return;
		const { scrollTop, scrollHeight, clientHeight } = scrollEl;
		const distanceFromBottom = scrollHeight - (scrollTop + clientHeight);
		if (distanceFromBottom < 200) {
			visibleCount = Math.min(visibleCount + PAGE_SIZE, fileNames.length);
		}
	}
</script>

<aside class="sidebar" style="width: {width}px; max-width: {SIDEBAR_MAX_WIDTH}px">
	<div class="header">
		<h2 class="title">{dataset.name}</h2>
		<div class="headerActions">
			<DownloadCaptions {fileNames} {captions} />
			<button
				type="button"
				class="closeBtn"
				onclick={onClose}
				title="Close"
			>
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M18 6L6 18M6 6l12 12" />
				</svg>
			</button>
		</div>
	</div>
	<div class="gallerySection">
		<div
			class="galleryScroll"
			bind:this={scrollEl}
			onscroll={handleScroll}
		>
			{#if isLoading}
				<p class="galleryEmpty">Loading…</p>
			{:else if fileNames.length === 0}
				<p class="galleryEmpty">No media files</p>
			{:else}
				<div class="galleryGrid">
					{#each visibleFiles as fileName}
						<div class="galleryItem">
							{#if !thumbLoaded[fileName]}
								<div class="thumbLoading">
									<div class="thumbSpinner"></div>
								</div>
							{/if}
							<video
								src={getDatasetMediaUrl(dataset.id, fileName)}
								class="galleryThumb"
								muted
								autoplay
								loop
								playsinline
								onloadeddata={() => {
									thumbLoaded = { ...thumbLoaded, [fileName]: true };
								}}
								onerror={() => {
									thumbLoaded = { ...thumbLoaded, [fileName]: true };
								}}
							></video>
							<div class="galleryCaption">
								<textarea
									value={captions[fileName] ?? ""}
									oninput={(e) =>
										handleCaptionChange(
											fileName,
											(e.target as HTMLTextAreaElement).value,
										)}
									placeholder="Caption"
									rows={2}
								></textarea>
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
	<div
		class="resizeHandle"
		class:resizeHandleActive={isDragging}
		use:resizable={resizableOpts}
		role="presentation"
	></div>
</aside>

<style>
	.sidebar {
		position: fixed;
		top: var(--header-height);
		right: 0;
		bottom: 0;
		display: flex;
		flex-direction: column;
		max-height: calc(100vh - var(--header-height));
		min-width: 320px;
		background: var(--surface);
		border-left: 1px solid var(--border);
		flex-shrink: 0;
		z-index: 50;
	}
	.resizeHandle {
		position: absolute;
		top: 0;
		left: 0;
		width: 6px;
		bottom: 0;
		cursor: col-resize;
		z-index: 1;
	}
	.resizeHandle:hover,
	.resizeHandleActive {
		background: rgba(99, 102, 241, 0.2);
	}
	.header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1rem 1.25rem;
		border-bottom: 1px solid var(--border);
		flex-shrink: 0;
	}
	.title {
		font-size: 1rem;
		font-weight: 600;
		margin: 0;
		color: var(--text);
	}
	.headerActions {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}
	.closeBtn {
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0.4rem;
		background: none;
		border: none;
		color: var(--text-dim);
		cursor: pointer;
		border-radius: var(--radius);
		transition: color 0.15s, background 0.15s;
	}
	.closeBtn:hover {
		color: var(--text);
		background: rgba(99, 102, 241, 0.08);
	}
	.closeBtn svg {
		width: 18px;
		height: 18px;
	}
	.gallerySection {
		flex: 1;
		display: flex;
		flex-direction: column;
		min-height: 0;
		overflow: hidden;
	}
	.galleryScroll {
		flex: 1;
		overflow-y: auto;
		padding: 1rem;
	}
	.galleryGrid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
		gap: 1rem;
	}
	.galleryItem {
		display: flex;
		flex-direction: column;
		position: relative;
		background: var(--bg);
		border: 1px solid var(--border);
		border-radius: var(--radius);
		overflow: hidden;
	}
	.galleryThumb {
		aspect-ratio: 16 / 9;
		object-fit: cover;
		width: 100%;
		background: var(--border);
	}
	.galleryCaption {
		font-size: 0.8rem;
	}
	.galleryCaption textarea {
		width: 100%;
		min-height: 2.5rem;
		padding: 0.4rem;
		font-size: 0.8rem;
		font-family: inherit;
		border: none;
		background: transparent;
		color: var(--text);
		resize: vertical;
	}
	.thumbLoading {
		position: absolute;
		inset: 0;
		display: flex;
		align-items: center;
		justify-content: center;
		background: radial-gradient(
			circle at center,
			rgba(15, 17, 23, 0.6),
			rgba(15, 17, 23, 0.9)
		);
		pointer-events: none;
	}
	.thumbSpinner {
		width: 24px;
		height: 24px;
		border-radius: 999px;
		border: 2px solid rgba(148, 163, 184, 0.4);
		border-top-color: var(--accent);
		animation: thumb-spin 0.7s linear infinite;
	}
	@keyframes thumb-spin {
		to {
			transform: rotate(360deg);
		}
	}
	.galleryEmpty {
		color: var(--text-dim);
		text-align: center;
		padding: 2rem;
	}
</style>
