// mg_custom_nodes/hao-ai-lab_FastVideo_20260405/ui/src/lib/components/CreateJobButton.svelte
<script lang="ts">
	import type { JobType } from "$lib/types";
	import { WORKLOAD_OPTIONS } from "$lib/jobConfig";
	import { triggerRefresh } from "$lib/stores/jobsRefresh";
	import CreateJobModal from "./CreateJobModal.svelte";

	let { jobType }: { jobType: JobType } = $props();

	let modalOpen = $state(false);
	const options = $derived(WORKLOAD_OPTIONS[jobType] ?? []);
	let workloadType = $state(options[0]?.type ?? "t2v");

	function openModal(type: string) {
		workloadType = type;
		modalOpen = true;
	}

	function handleSuccess() {
		triggerRefresh();
		modalOpen = false;
	}
</script>

<div class="wrapper">
	<button type="button" class="btn btnPrimary trigger">Create Job</button>
	<div class="menu" role="menu">
		{#each options as opt}
			<button
				type="button"
				class="menuItem"
				role="menuitem"
				onclick={() => openModal(opt.type)}
			>
				{opt.label}
				<div class="menuItemDesc">{opt.desc}</div>
			</button>
		{/each}
	</div>
</div>
<CreateJobModal
	isOpen={modalOpen}
	onClose={() => (modalOpen = false)}
	onSuccess={handleSuccess}
	{jobType}
	{workloadType}
/>

<style>
	.wrapper {
		position: relative;
		display: inline-block;
	}
	.trigger {
		display: flex;
		align-items: center;
		gap: 0.35rem;
	}
	.trigger::after {
		content: "";
		width: 0;
		height: 0;
		border-left: 4px solid transparent;
		border-right: 4px solid transparent;
		border-top: 5px solid currentColor;
		opacity: 0.85;
	}
	.menu {
		position: absolute;
		top: 100%;
		right: 0;
		margin-top: 0.25rem;
		min-width: 100%;
		background: var(--bg);
		border: 1px solid var(--border);
		border-radius: var(--radius);
		box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
		padding: 0.25rem 0;
		opacity: 0;
		visibility: hidden;
		transform: translateY(-4px);
		transition: opacity 0.15s, visibility 0.15s, transform 0.15s;
		z-index: 200;
	}
	.wrapper:hover .menu {
		opacity: 1;
		visibility: visible;
		transform: translateY(0);
	}
	.menuItem {
		display: block;
		width: 100%;
		padding: 0.5rem 1rem;
		border: none;
		background: transparent;
		color: var(--text);
		font-family: inherit;
		font-size: 0.9rem;
		font-weight: 500;
		text-align: left;
		cursor: pointer;
		transition: background 0.1s;
		white-space: nowrap;
	}
	.menuItem:hover {
		background: var(--border);
	}
	.menuItemDesc {
		font-size: 0.75rem;
		color: var(--text-dim);
		font-weight: 400;
		margin-top: 0.1rem;
	}
	.btn {
		cursor: pointer;
		border: none;
		border-radius: var(--radius);
		font-family: inherit;
		font-weight: 600;
		font-size: 0.85rem;
		padding: 0.55rem 1.2rem;
	}
	.btnPrimary {
		background: var(--accent);
		color: #fff;
	}
</style>

// mg_custom_nodes/hao-ai-lab_FastVideo_20260716/apps/fastvideo_studio/src/components/jobs/CreateJobButton.tsx
'use client';

import * as React from 'react';
import { ChevronDown } from 'lucide-react';

import CreateJobModal from '@/components/jobs/CreateJobModal';
import { Button } from '@/components/ui/button';
import { WORKLOAD_OPTIONS } from '@/lib/jobConfig';
import type { JobType } from '@/lib/types';
import { triggerRefresh } from '@/stores/jobsRefresh';

interface CreateJobButtonProps {
  jobType: JobType;
}

export default function CreateJobButton({ jobType }: CreateJobButtonProps) {
  const options = WORKLOAD_OPTIONS[jobType] ?? [];

  const [modalOpen, setModalOpen] = React.useState(false);
  const [workloadType, setWorkloadType] = React.useState(
    options[0]?.type ?? 't2v',
  );

  function openModal(type: string) {
    setWorkloadType(type);
    setModalOpen(true);
  }

  function handleSuccess() {
    triggerRefresh();
    setModalOpen(false);
  }

  return (
    <>
      <div className="group relative inline-block">
        <Button type="button" className="gap-1.5">
          Create Job
          <ChevronDown className="size-3.5 opacity-85" aria-hidden />
        </Button>
        <div
          role="menu"
          className="invisible absolute right-0 top-full z-[200] mt-1 min-w-full -translate-y-1 rounded-lg border border-border bg-popover py-1 opacity-0 shadow-lg transition-all duration-150 group-hover:visible group-hover:translate-y-0 group-hover:opacity-100"
        >
          {options.map((opt) => (
            <button
              key={opt.type}
              type="button"
              role="menuitem"
              onClick={() => openModal(opt.type)}
              className="block w-full whitespace-nowrap px-4 py-2 text-left text-sm font-medium text-popover-foreground transition-colors hover:bg-secondary"
            >
              {opt.label}
              <span className="mt-0.5 block text-xs font-normal text-muted-foreground">
                {opt.desc}
              </span>
            </button>
          ))}
        </div>
      </div>
      <CreateJobModal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        onSuccess={handleSuccess}
        jobType={jobType}
        workloadType={workloadType}
      />
    </>
  );
}
